@startuml

'pour cacher les attributs dans les diff class'
hide empty members

abstract class Joueur {

}

class Carte {

}

class Jeu {
    Jeu() : void
    nouvellePartie () : void
    
}

class PLI {

}

class Tas {

}

class Tour {

}

enum Atout {

}

class JHumain {

}

class JIA {

}

class Excuse {
    valMax : boolean
    compareTo(atout Atout): int
    compareTo(excuse Excuse): int
}

interface ICarte {

    compareTo(atout Atout): int
    compareTo(excuse Excuse): int

}


PLI "1" *.. "0..4" Carte
Tas "1" *.. "0..22" Carte

Joueur <|-- JHumain
Joueur <|-- JIA

Tour o-- "0..5" PLI
Jeu o-- "4" Joueur
Jeu o-- Tour

Atout ..> ICarte
Excuse ..> ICarte
Carte o.. ICarte


@enduml