@startuml

'pour cacher les attributs dans les diff class'
hide empty members

abstract class Joueur {
    -nbVie : int
    -nom : String
    paris(paris : int)
    Joueur(Nom : String)
}

class Carte {

}

class Jeu {
    -joueur : IJoueur[4]
    -joueurCourant : IJoueur
    --
    Jeu() : void
    nouvelleTour () : void
    joueur () : void
    partieTerminer () : void
}

interface IJoueur {
    +jouer: void
    +choisirCarte : Carte
}

class PLI {

}

class Tas {

}

class Tour {
    -NumeroTour : int
    +distribueCarte() : void
}

enum Atout {

}

class JHumain {

}

class JIA {

}

class Excuse {
    -valMax : boolean
    +compareTo(atout Atout): int
    +compareTo(excuse Excuse): int
}

interface ICarte {
    +compareTo(atout Atout): int
    +compareTo(excuse Excuse): int

}


PLI "1" *.. "0..4" Carte
Tas "1" *.. "0..22" Carte

Joueur <|-- JHumain
Joueur <|-- JIA

Tour o-- "0..5" PLI
Jeu o-- Tour

Atout ..|> ICarte
Excuse ..|> ICarte
Carte -- ICarte

Jeu o-- "2" IJoueur
IJoueur <|.. Joueur

@enduml